# Generated by Django 5.0.6 on 2024-07-20 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('tipousuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordene',
            fields=[
                ('ordenid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaorden', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.CharField(max_length=10)),
                ('iva', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='img/productos/')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('preciouf', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalleordene',
            fields=[
                ('detalleid', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
                ('totalvalorprod', models.CharField(max_length=10)),
                ('ordenid', models.ForeignKey(db_column='ordenid', on_delete=django.db.models.deletion.CASCADE, to='appEasytruck.ordene')),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='appEasytruck.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carritoid', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
                ('totalvalorprod', models.CharField(max_length=10)),
                ('subtotal', models.CharField(max_length=10)),
                ('iva', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='appEasytruck.producto')),
            ],
        ),
    ]
