# Generated by Django 5.0.6 on 2024-07-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEasytruck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
