# Generated by Django 5.0.6 on 2024-07-24 17:17

import appEasytruck.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEasytruck', '0002_alter_producto_descripcion_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to=appEasytruck.models.generate_unique_filename),
        ),
    ]
