# Generated by Django 5.0.6 on 2024-07-16 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=50)),
                ('apellidoCliente', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('emailCliente', models.CharField(max_length=50)),
                ('passwordhashCliente', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('tipousuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordene',
            fields=[
                ('ordenid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaorden', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.CharField(max_length=10)),
                ('iva', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('clienteid', models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Detalleordene',
            fields=[
                ('detalleid', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
                ('totalvalorprod', models.CharField(max_length=10)),
                ('ordenid', models.ForeignKey(db_column='ordenid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.ordene')),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carritoid', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('cantidad', models.CharField(max_length=10)),
                ('totalvalorprod', models.CharField(max_length=10)),
                ('subtotal', models.CharField(max_length=10)),
                ('iva', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('clienteid', models.ForeignKey(db_column='clienteid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.cliente')),
                ('productoid', models.ForeignKey(db_column='productoid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('passwordhash', models.CharField(max_length=50)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('tipousuario', models.ForeignKey(db_column='tipousuarioid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.tipo_usuario')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='usuarioid',
            field=models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='appRecytruck.usuario'),
        ),
    ]
